export const FETCH_QUERY_STRING = 'FETCH_QUERY_STRING';
export const GET_ABLUM_IMG_URLS = 'GET_ABLUM_IMG_URLS';
export const GET_ALBUM_IDS = 'GET_ALBUM_IDS';
export const SET_PLAYER_ID = 'SET_PLAYER_ID'
export const SET_PLAYING_TRUE = 'SET_PLAYING_TRUE'
export const SET_PLAYING_FALSE = 'SET_PLAYING_FALSE'